#!/usr/bin/env python

import sys, os

if len(sys.argv) != 3:
  exit()

new_tab = sys.argv[1] == '1'
arg = sys.argv[2].upper()
if '-' not in arg:
  arg = 'NI-' + arg

qute_fifo = os.environ.get('QUTE_FIFO')
with open(qute_fifo, 'a') as f:
  args = []
  args.append('open')
  if new_tab:
    args.append('-t')
  args.append(f'courses.fit.cvut.cz/{arg}')
  print(' '.join(args), file=f)
