#!/run/current-system/sw/bin/python

import sys
from utils import *

if len(sys.argv) != 3:
  exit()

new_tab = sys.argv[1] == '1'
arg = sys.argv[2].upper()
if '-' not in arg:
  arg = 'NI-' + arg

args = []
args.append('open')
if new_tab:
  args.append('-t')
args.append(f'courses.fit.cvut.cz/{arg}')

send(args)
