#!/usr/bin/env bash

if [[ $(hostname) == *"pc" ]]; then
  echo DESKTOP
  script=./desktop.js
else
  echo LAPTOP
  script=./laptop.js
fi

while true; do
  pkill ags
  echo '--- STARTING ---'
  bash -c "ags1 -c '$script' -b bar &"
  read -r -n 1 cmd
  if [ "${cmd}" == "a" ]; then
    break
  fi
done
