#!/usr/bin/env bash

if [[ $(hostname) == *"pc" ]]; then
  echo DESKTOP
  script=./desktop.js
else
  echo LAPTOP
  script=./laptop.js
fi

while true; do
  pkill ags
  echo '--- STARTING ---'
  bash -c "ags -c '$script' -b bar &"
  read
done
