monitor=DP-1, 2560x1440@165, 0x0, 1
monitor=DP-2, 2560x1440@165, 5120x0, 1
monitor=DP-3, 2560x1440@165, 2560x0, 1

workspace = 1000, monitor:DP-1, default:true
workspace = 1010, monitor:DP-3, default:true
workspace = 1020, monitor:DP-2, default:true

$mainMod = SUPER

exec-once = ags1 -c ~/.config/ags/desktop.js -b bar

# fix for nvidia games (don't know if it actually does anything)
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
cursor {
  no_hardware_cursors = true
}
